<?php
/**
 * Replanta Heartbeat Control
 * Optimizes WordPress Heartbeat API to reduce server load.
 * Generated by Replanta Site Audit.
 */

// Disable Heartbeat on dashboard and most pages
add_action('init', function() {
    // Allow on post edit screens for autosave
    global $pagenow;
    if (!in_array($pagenow, ['post.php', 'post-new.php'])) {
        wp_deregister_script('heartbeat');
    }
}, 1);

// Slow down Heartbeat where it's needed (post edit)
add_filter('heartbeat_settings', function($settings) {
    $settings['interval'] = 120; // 120 seconds instead of default 15-60
    return $settings;
});